version: '3.8'

services:
  SRBMiner-Multi:
    tty: true
    image: cecepabdul/srbminer
    restart: always
    environment:
      ALGO: aurum
      POOL_ADDRESS: stratum-na.rplant.xyz:7114
      WALLET_USER: waf1qe4ua6d3h2een65sd5uphz6s02x7p8dfurh7ap7
      WORKER: paas
      PASSWORD: webpassword=cecepabdul
